// Generated by CoffeeScript 1.9.1
(function() {
  var fields;

  fields = require("./Fields");

  module.exports = {
    fields: fields,
    utils: require("./utils"),
    localized: {
      en: {
        fields: require("./localized/en/Fields"),
        us_states: require("./localized/en/us_states")
      }
    },
    genField: fields.genField
  };

}).call(this);
