// Generated by CoffeeScript 1.9.1
(function() {
  var X;

  X = (function() {
    function X(opts, x, y) {
      console.log(opts, x, y);
    }

    return X;

  })();

  module.exports = X;

}).call(this);
